# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)"
])

# A list of supported languages
languages([
  "en-US",
  "zh-Hans"
])

# The name of the scheme which contains the UI Tests
scheme("umbrella")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments([
  "-UIPreferredContentSizeCategoryName regular"
])

# The directory where to store the screenshots
# output_directory('./screenshots')

# The directory where to store the reference screenshots
# reference_screenshots_directory('./reference_screenshots')

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Skip opening the HTML report after running snapshot
skip_open_summary(true)

# Skip running the tests when snapshot is called
# skip_tests(true)

# For more information about all available options run
# fastlane snapshot --help
